language: python


matrix:
  include:
    - name: "ubuntu xenial"
      os: linux  
      dist: xenial
    - name: "ubuntu bionic"
      os: linux
      dist: bionic

python:
  - "3.6"

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh							 
  - ./miniconda.sh -b
  - export PATH=$HOME/miniconda3/bin:$PATH
  - conda update --yes conda
  - conda config --add channels defaults
  - conda config --add channels conda-forge
  - conda config --add channels bioconda
  
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION snakemake ncbi-genome-download r-base r-argparse r-curl r-data.table r-dplyr
  - conda list
  - wget http://ftp.tue.mpg.de/ebio/projects/struo/misc/uniref50.ec_filtered.1.1.dmnd
  - wget -q -O - https://data.ace.uq.edu.au/public/gtdb/data/releases/release89/89.0/ar122_metadata_r89.tsv | head -n 6 > metadata_n5.tsv
  - tail -n +2 metadata_n5.tsv | cut -f 1 > accessions.tsv

script:
#  - snakemake --use-conda --configfile tests/config_default.yaml
   - /util_scripts/GTDB_metadata_filter.R https://data.ace.uq.edu.au/public/gtdb/data/releases/release89/89.0/ar122_metadata_r89.tsv | head -n 100
   - ./util_scripts/genome_download.R metadata_n5.tsv
   - ./util_scripts/tree_prune.py accessions.tsv https://data.ace.uq.edu.au/public/gtdb/data/releases/release89/89.0/ar122_r89.tree
